### ISSUE TITLE
BigFloat precision issue

### ISSUE THREAD

**Issue by newtmex** [multiversx/mx-sdk-rs#1230]
Hi, I noticed that converting a `BigFloat` number to `BigUint` using the `to_fixed_point` method breaks when the precision (denominator) is greater than `10^16`.

e.g
```rust
let exp = 1_080i32;

BigFloat::from_sci(1_005, -3).pow(exp)
   .to_fixed_point(&(1_000_000_000_000_000_00i64.into()))
   .into_big_uint()
// This gives 9223372036854775807, which is wrong

BigFloat::from_sci(1_005, -3).pow(exp)
   .to_fixed_point(&(1_000_000_000_000_000_0i64.into()))
   .into_big_uint()
// This gives the expected answer: 3597102991946283520
```

Maybe I am doing something wrong; please advise.

**Comment by mihaicalinluca** [comment]
Hi, 
It seems like you have reached the limit of float64. :)

This is not an actual issue with the framework, but more of an issue with choosing the right tool for the problem you are facing.

If you need help with finding a better solution you can drop a message with the description of your problem on our community Telegram or Discord servers so that we can receive more context. 

You can find all the links here:
https://linktr.ee/multiversx
